---
title: "Meta-Workflow"
author: "Miao Yu"
date: "August 16, 2016"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache = T,message=T,warning=F)
sessionInfo()
```

# Optimization

```{r IPOpos,eval=FALSE}
library(IPO)
library(xcms)
peakpickingParameters <- getDefaultXcmsSetStartingParams('centWave')
# Demo data
path <- system.file("extdata/data", package = "rmwf")
files <- list.files(path,recursive = T,full.names = T)
# Uncomment this line to use your own data(suggested 3-5 pooled QC samples)
# path <- 'path/to/your/files'
# change to 5 for obitrap
peakpickingParameters$ppm <- 10
resultPeakpicking <- 
  optimizeXcmsSet(files = files[c(7,9,11)], 
                  params = peakpickingParameters,
                  plot = F,
                  subdir = NULL)

optimizedXcmsSetObject <- resultPeakpicking$best_settings$xset
retcorGroupParameters <- getDefaultRetGroupStartingParams()
resultRetcorGroup <-
  optimizeRetGroup(xset = optimizedXcmsSetObject, 
                   params = retcorGroupParameters, 
                   plot = F,
                   subdir = NULL)
para <- c(resultPeakpicking$best_settings$parameters, 
          resultRetcorGroup$best_settings)
save(para,file = 'para.RData')
```

# Wrap function

```{r eval=T}
library(xcms)
library(stringr)
# here we use pre-optimized IPO parameters
# data('para')
load('para.RData')
getrtmz <- function(path,index = NULL){
  files <- list.files(path,full.names = T,recursive = T)
  if(!is.null(index)){
    files <- files[index]
  }
  xset <- xcmsSet(files,
                  method = "centWave",
                  peakwidth       = c(para$min_peakwidth,para$max_peakwidth),
                  ppm             = para$ppm,
                  noise           = para$noise,
                  snthresh        = para$snthresh,
                  mzdiff          = para$mzdiff,
                  prefilter       = c(para$prefilter,para$value_of_prefilter),
                  mzCenterFun     = para$mzCenterFun,
                  integrate       = para$integrate,
                  fitgauss        = para$fitgauss,
                  verbose.columns = para$verbose.columns)
  xset <- retcor( 
    xset,
    method         = para$retcorMethod,
    plottype       = para$plottype,
    distFunc       = para$distFunc,
    profStep       = para$profStep,
    center         = para$center,
    response       = para$response,
    gapInit        = para$gapInit,
    gapExtend      = para$gapExtend,
    factorDiag     = para$factorDiag,
    factorGap      = para$factorGap,
    localAlignment = para$localAlignment)
  xset <- group( 
    xset,
    method  = "density",
    bw      = para$bw,
    mzwid   = para$mzwid,
    minfrac = para$minfrac,
    minsamp = para$minsamp,
    max     = para$max)
  
  xset <- fillPeaks(xset)
  return(xset)
}
```

# Peaks list

This chunk is used to generate peaks list and related csv, xcmsset object, xcmsEIC object for further analysis.

```{r eval=F}
# get the xcmsset object from demo data
path <- system.file("extdata/data", package = "rmwf")
# use your own data
# path <- 'path/to/your/file'
srm <- getrtmz(path)
# back up the xcmsset object, xcmsEIC object and peak list
mzrt <- enviGCMS::getmzrt(srm, name = 'srm', eic = T, type = 'mapo')
```

# Data visulization

```{r}
# you could load you eic and xset object, here is the demo data
data("srmeic")
data("srmxset")
# EIC for m/z 239.0911(four digits) and retention time 229.4s(one digits)
plot(srmeic,srmxset,groupidx = 'M239.0911T229.4')
# PCA
enviGCMS::plotpca(data = mzrtfilter$data,lv = mzrtfilter$group)
# mzrt plot
enviGCMS::plotmr(mzrtfilter)
# RSD plot
enviGCMS::plotrsd(mzrtfilter)
# density plot
enviGCMS::plotden(mzrtfilter$data,lv=mzrtfilter$group,ylim = c(0,1))
# heatmap
enviGCMS::plothm(mzrtfilter$data,lv=factor(mzrtfilter$group),index = c(1:20))
# TSNE
# rtsne_out <- Rtsne::Rtsne(t(mzrtfilter$data))
# plot(rtsne_out)
# visulize the batch effect/run order effects
enviGCMS::plotrla(mzrt$data,lv = as.factor(mzrt$group))
enviGCMS::plotridges(mzrt$data,lv = factor(mzrt$group))
```

# Peaks filtering

```{r}
data(mzrt)
# get the mean and rsd for each group
mzrtm <- enviGCMS::getdoe(mzrt)
gm <- mzrtm$groupmean
gr <- mzrtm$grouprsd
# find the blank group and pool QC group, demo data only have matrix blank
srm <- grepl('NIST',colnames(gm))
blk <- grepl('Matrix',colnames(gm))
# pqc <- grepl('pool',colnames(gm))
# filter by pool QC and blank's group mean intensity(pool QC should larger than three times of blank), return numbers and index
# in demo data, use sample average intensity for each peak
sum(indexmean <- apply(gm,1,function(x) all(x[srm]>= 3*x[blk])))
# filter by pool qc rsd%, return numbers and index
# in demo data, use sample average intensity for each peak
# mean rsd analysis
library(tidyverse)
a <- cbind.data.frame(NISTmean = gm[,1],NISTrsd = gr[,1])
p <- ggplot(a,aes(x=log10(NISTmean),y=NISTrsd)) +
        ggtitle("Mean vs. RSD%") +
        xlab("log10(Mean)") +
        ylab("rsd%") 
# Visualization 1
p1 <-  p + 
  geom_point(alpha = 0.5, colour="orange")+
        geom_density2d()
p1
# Visualization 2
p2 <- p +
  stat_bin_hex(colour="white", na.rm=TRUE) +
  scale_fill_gradientn(colours=c("red","orange"), name = "Frequency", na.value=NA)
p2
# Visualization 3
smoothScatter(x=log10(a$NISTmean),y=a$NISTrsd)
# select rsd% cutoff around 30
rsdcf <- 30
sum(indexrsd <- apply(gr,1,function(x) ifelse(is.na(x[srm]),T,x[srm]<rsdcf)))
# overlap with rsd% and mean filter
sum(index <- indexmean&indexrsd)

# new list, update group and remove pool qc/blk and save the new csv file
qcindex <- grepl('blank',mzrt$group) | grepl('pool',mzrt$group)
mzrtfilter <- enviGCMS::getfilter(mzrt,rowindex = index,colindex = !qcindex, name = 'lif', type = 'm')
```

# Normalization (Optional)

```{r}
# visulize the batch effect
mzrtsim::rlaplot(mzrt$data,lv = mzrt$group$class)
mzrtsim::ridgesplot(mzrt$data,lv = mzrt$group$class)
# get the simulation data and test on NOREVA
sim <- mzrtsim::simmzrt(mzrt$data)
mzrtsim::simdata(sim)
```

# Statistical analysis

```{r}
# visulize the data
enviGCMS::plotmr(mzrtfilter,inscf = 4,rsdcf = 50)
# PCA
#enviGCMS::plotpca(mzrtfilter$data,
#                  as.character(mzrtfilter$group))
enviGCMS::plotpca(mzrtfilter$data,c('b','b','b','M','M','M','H','H','H','L','L','L'))

library(caret)
## Spliting data
trainIndex <- createDataPartition(mzrtfilter$data, p = .8, 
                                  list = FALSE, 
                                  times = 1)
## Get the training and testing datasets
Train <- data[ trainIndex,]
Test  <- data[-trainIndex,]
## Set the cross validation method
fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv",
                           number = 10,
                           ## repeated ten times
                           repeats = 10)
# extra papameters for GBM 
gbmGrid <-  expand.grid(interaction.depth = c(1, 5, 9), 
                        n.trees = (1:30)*50, 
                        shrinkage = 0.1,
                        n.minobsinnode = 20)

set.seed(825)
gbmFit <- train(mzrtfilter$group ~ ., data = training, 
                 method = "gbm", 
                 trControl = fitControl, 
                 verbose = FALSE, 
                 ## Now specify the exact models 
                 ## to evaluate:
                 tuneGrid = gbmGrid)
# show the fitting process
plot(gbmFit)  
# ANOVA analysis for model selection
anova(fit1,fit2)
# find the important variables
Imp <- varImp(fit)
plot(Imp)
```

# Annotation

```{r eval=FALSE}
library(xMSannotator)
data("adduct_weights")
data <- mzrtfilter$data
mz <- mzrtfilter$mz
time <- mzrtfilter$rt
data <- as.data.frame(cbind(mz, time, data))
data <- unique(data)
num_nodes = 4
xMSannotator::multilevelannotation(
                                        dataA = data,
                                        max.mz.diff = 5,
                                        mode = 'pos',
                                        outloc = 'anno',
                                        db_name = 'HMDB',
                                        adduct_weights = adduct_weights,
                                        filter.by = c("M+H"),
                                        mass_defect_mode = 'pos',
                                        num_nodes = 4
)
# annolipid <- xsetplus::fanno(neg,outloc = 'D:/storage/data/anno',
#                              db_name = 'LipidMaps')
```

# Pathway Analysis

```{r pathway}
# get the file
xsetplus::mumdata(neg,lv = mzrt$group$class)
# http://mummichog.org/index.html
# mummichog1 -f 'test.txt' -o myResult
```

# PMD analysis

```{r pmd}
load('neg.Rdata')
list <- enviGCMS::getmzrt(neg,name = 'pmd')
pmd <- pmd::globalstd(list)
lif <- enviGCMS::getfilter(pmd,rowindex = pmd$stdmassindex)
# output csv file for metaboanalyst
enviGCMS::getcsv(lif,'pmd',type = 'm')
```

